name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Clone submodules
      run: git submodule update --init --recursive
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Configure
      run: cmake -H. -B_build -DBUILD_TESTS=ON
      
    - name: Build
      run: cmake --build _build
      
    - name: Run tests
      run: cd _build && ./RunTest
      
    - name: Generate coverage data
      working-directory: _build
      run: |
        lcov --capture \
          --directory . \
          --output-file coverage.info \
          --ignore-errors mismatch,unused \
          --rc branch_coverage=1 \
          --rc geninfo_unexecuted_blocks=1
        
    - name: Filter coverage results
      working-directory: _build
      run: |
        lcov --remove coverage.info \
          '/usr/*' \
          '*/external/*' \
          '*/test/*' \
          '*/gtest/*' \
          '*/gmock/*' \
          --output-file filtered.info \
          --ignore-errors unused
        
    - name: Generate HTML report
      working-directory: _build
      run: |
        genhtml --branch-coverage \
          --title "Test Coverage Report" \
          --legend \
          --output-directory coverage \
          filtered.info \
          --ignore-errors unmapped,unused
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: _build/coverage
