name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Clone submodules
      run: git submodule update --init --recursive
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Configure
      run: cmake -H. -B_build -DBUILD_TESTS=ON
      
    - name: Build
      run: cmake --build _build
      
    - name: Run tests
      run: cd _build && ./RunTest
      
    - name: Coverage
      run: |
        sudo apt-get install -y lcov
        cd _build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info
